feat: Repair the instrument panel and Echarts components. The indicator name should be filled in
masastack/MASA.TSC pull request #145
Opened 2023-02-23 11:12 UTC by kogel-net

2023-02-23 12:30 UTC, doddgu requested changes

2023-02-23 12:30 UTC, doddgu commented on src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Panel/Chart/ChartPanelConfiguration.razor.cs
> +            return;
Return is meaningless.

2023-02-23 12:30 UTC, doddgu commented on src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Panel/Chart/ChartPanelConfiguration.razor.cs
> +    async Task NavigateToPanelConfigurationPage()
NavigateToPanelConfigurationPageAsync

2023-02-23 12:30 UTC, doddgu commented on src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Panel/Chart/ChartPanelConfiguration.razor.cs
> +    async Task Cancel()
CancelAsync

2023-02-24 06:17 UTC, kogel-net commented
Updated

2023-02-24 06:29 UTC, 15168440402 commented
> Updated

![图片](https://user-images.githubusercontent.com/30889371/221108154-540d3d93-86d9-4394-b71d-8773548168c2.png)

2023-02-24 06:35 UTC, kogel-net commented
> > Updated
> 
> ![图片](https://user-images.githubusercontent.com/30889371/221108154-540d3d93-86d9-4394-b71d-8773548168c2.png)

updated

2023-02-24 07:07 UTC, 15168440402 commented
![图片](https://user-images.githubusercontent.com/30889371/221114522-bdfec843-0128-4451-94ae-3cbeb6de837b.png)
The prompt information is inconsistent with the TextField Label

2023-02-24 07:28 UTC, 15168440402 commented
LGTM

2023-02-24 07:28 UTC, 15168440402 approved these changes

2023-02-24 07:32 UTC, kogel-net commented on src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Panel/Chart/ChartPanelConfiguration.razor.cs
> +            await PopupService.AlertAsync(T("Name is required"), AlertTypes.Error);
updated

2023-02-24 07:33 UTC, merged