feat(log\trace):team、 log and trace init
masastack/MASA.TSC pull request #2
Opened 2022-08-08 10:05 UTC by Qinyouzeng

- team over-view
- log search
- trace list and detail

2022-08-09 06:18 UTC, doddgu requested changes

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Extensions/IElasticClientExtenstion.cs
> +            var find = FieldMaps.First(m => m.Alias == item.Key);
find?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Extensions/IElasticClientExtenstion.cs
> +                string tem = default!;
tem?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Infrastructure/EntityConfigurations/InstrumentEntityConfiguration.cs
> +        //builder.HasMany(x => x.Pannels).WithOne();
Why comment it? If don't use it anymore, delete it.

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Infrastructure/EntityConfigurations/MetricEntityConfiguration.cs
> +        //builder.Property(x => x.Title).HasMaxLength(200).IsRequired();
?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Infrastructure/Middleware/LogMiddleware.cs
> +//namespace Masa.Tsc.Service.Infrastructure.Middleware
Why comment it?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Infrastructure/Repositories/PannelRepository.cs
> +public class PannelRepository : Repository<TscDbContext, Pannel, Guid>, IPannelRepository
Panel

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Program.cs
> +var elasearchUrls = builder.Configuration.GetSection("Masa:Elastic:nodes").Get<string[]>();
elasearch?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Program.cs
> +        //var xmlFilename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Program.cs
> +    //new AuthDbContextSeed().SeedAsync(context, logger).Wait();
?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Services/ProjectService.cs
> +        App.MapGet($"{BaseUri}/over-view", OverViewAsync);
overview

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Services/TeamService.cs
> +        var teamQuery = new TeamDetailQuery(Guid.Empty, appId);
The `teamId` has not been used?

2022-08-09 06:18 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Services/TraceService.cs
> +        ////var text = "{\"accounts\":[{\"accountID\":\"00000000-0000-0000-0000-000000000000\",\"accountNum\":\"test00001\",\"blocked\":0,\"city\":\"温州市\",\"countryRegionId\":\"CHN\",\"county\":\"乐清市
?

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin.Server/Program.cs
> +using Masa.BuildingBlocks.Identity.IdentityModel;
Move these to _Imports.

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin.Server/Program.cs
> +
Remove the blank line.

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin.Server/TokenProvider.cs
> +//public class TokenProvider : ITokenProvider
?

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin.Server/appsettings.Development.json
> +      "ServiceName": "tsc.web",
?

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin.WebAssembly/Program.cs
> +//builder.Services.AddSingleton<WeatherForecastService>();
?

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin/Data/Trace/TraceDetailModel.cs
> +
Remove the blank line

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin/Extensitions/ObservableExtensions.cs
> +
Remove the blank line.

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin/Extensitions/ObservableExtensions.cs
> +
Remove the blank line.

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin/Global/MenuConfigs.cs
> +    //public static void Register(string text, string url, string parent)
?

2022-08-09 06:18 UTC, doddgu commented on src/Web/Masa.Tsc.Admin/Global/MenuConfigs.cs
> +        //_menus.Add(new)
?

2022-08-10 05:41 UTC, Qinyouzeng commented on src/ApiGateways/Caller/Masa.Tsc.Caller/Services/DirectoryService.cs
> +    public DirectoryService(ICallerProvider caller) : base(caller, "/api/Instrument/directory") { }
Directory is a subfunction.

2022-08-10 08:51 UTC, doddgu requested changes

2022-08-10 08:51 UTC, doddgu commented on src/Contracts/Masa.Tsc.Contracts.Admin/Charts/ChartViewDto.cs
> +    /// x value raw toString, like '8' 、'8.00'、'8.00%'
x value?

2022-08-10 08:51 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Application/Traces/QueryHandler.cs
> +            pageration: () => ValueTuple.Create(false, 0, ElasticConst.MAX_DATA_COUNT - 1),
pageration?

2022-08-10 08:51 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Program.cs
> +    .AddTransient(typeof(IMiddleware<>), typeof(LogMiddleware<>))
code format

2022-08-10 08:51 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/Services/TraceService.cs
> +    private async Task<ChartLineDataDto<ChartPointDto>> GetAggregateAsync([FromServices] IEventBus eventBus, [FromBody] RequestAggregationDto param)
Get is v, Aggregate is v too.

2022-08-10 08:51 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/appsettings.Develop.json
> +  "Masa": {
Masa is same level with DccOptions?

2022-08-10 08:51 UTC, doddgu commented on src/Services/Masa.Tsc.Service.Admin/appsettings.Development.json
> +    "OtlpUrl": "http://otel.lonsid.cn:32247",
Is this internal domain?

2022-08-10 08:51 UTC, doddgu commented on src/Web/Masa.Tsc.Web.Admin.Server/Pages/Error.cshtml.cs
> +[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
Why need ResponseCache?

2022-08-10 08:51 UTC, doddgu commented on src/Web/Masa.Tsc.Web.Admin.Server/appsettings.Development.json
> +  "otlpUrl": "http://otel.lonsid.cn:32247",
Is this internal domain?

2022-08-10 08:51 UTC, doddgu commented on src/Web/Masa.Tsc.Web.Admin/Shared/MainLayout.razor
> +    }
code format

2022-08-10 09:45 UTC, Qinyouzeng commented on src/Web/Masa.Tsc.Web.Admin.Server/appsettings.Development.json
> +  "otlpUrl": "http://otel.lonsid.cn:32247",
No, 域名的现在外网可访问，ip是内网，我已经告诉了王静克，他明天再调整下

2022-08-10 09:46 UTC, Qinyouzeng commented on src/Web/Masa.Tsc.Web.Admin.Server/appsettings.Development.json
> +  "otlpUrl": "http://otel.lonsid.cn:32247",
确认了，只有内网可以访问

2022-08-10 09:57 UTC, Qinyouzeng commented on src/Contracts/Masa.Tsc.Contracts.Admin/Charts/ChartViewDto.cs
> +    /// x value raw toString, like '8' 、'8.00'、'8.00%'
echart数据展示时，x轴数据和y轴数据需要分开设置，这个地方设置的为y轴的纵坐标数据

2022-08-12 05:47 UTC, doddgu requested changes

2022-08-12 05:47 UTC, doddgu commented on src/Contracts/Masa.Tsc.Contracts.Admin/Charts/ChartViewDto.cs
> +    /// y value raw toString, like '8' 、'8.00'、'8.00%'
What's the mean of Y?

2022-08-12 07:53 UTC, doddgu approved these changes
LGTM

2022-08-12 08:37 UTC, merged